
source 'https://github.com/CocoaPods/Specs.git'   # 官方库地址
source 'https://gitee.com/lkb_shidaiwanwang/pod_one.git'  # 私有仓库地址

platform :ios, '8.0'


target 'test' do


pod ‘ppp’

pod ‘lkb_pod_one’
  



end
